#!/bin/bash

#COMPILE AND RUN UNIT TESTS

CP=".:deps/hamcrest-core-1.3.jar:deps/junit-4.13-beta-1.jar:deps/sqlite-jdbc-3.23.1.jar"

SRC_FILES="Database.java\
           DatabaseTest.java"

javac -cp $CP $SRC_FILES

TESTS='DatabaseTest'

java -cp "$CP" org.junit.runner.JUnitCore $TESTS






#COMPILE AND RUN SERVER

CP='.:deps/sqlite-jdbc-3.23.1.jar:deps/nanohttpd-2.3.1.jar'

SRC_FILES="TrackerServer.java\
           Database.java\
           Network.java"

javac -cp $CP $SRC_FILES

java -cp $CP TrackerServer
